# Based on https://github.com/travier/fedora-kinoite/blob/main/.github/workflows/fedora-kinoite.yml

name: "Build Fedora Kinoite image"

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: fedora-kinoite
  BASE_IMAGE: quay.io/fedora/fedora-kinoite:latest

on:
  schedule:
    - cron: '0 2 * * *'
  pull_request:
    branches:
      - main
    paths:
      - 'fedora-kinoite/**'
      - '.github/workflows/fedora-kinoite.yml'
  push:
    branches:
      - main
    paths:
      - 'fedora-kinoite/**'
      - '.github/workflows/fedora-kinoite.yml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Override version label (org.opencontainers.image.version)'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-latest

    container: 
      image: quay.io/containers/podman
      options: --privileged --volume /:/run/host:rw --user 0:0

    permissions:
      contents: read
      packages: write

    outputs:
      digest: ${{ steps.push.outputs.digest }}
      registry: ${{ env.REGISTRY }}
      image: ${{ steps.relabel.outputs.image }}

    steps:
      - name: Downcase REGISTRY
        run: |
          echo "REGISTRY=${REGISTRY,,}" >> ${GITHUB_ENV}

      - name: Reclaim disk space
        run: |
          set -euxo pipefail
          rm -rf \
          /run/host/usr/share/dotnet \
          /run/host/usr/local/lib/android \
          /run/host/opt/ghc \
          /run/host/opt/hostedtoolcache/CodeQL \
          /run/host/usr/local/share/boost

      - name: Install prereqs
        run: |
          set -euxo pipefail
          dnf upgrade -y --refresh
          dnf install -y buildah skopeo rpm-ostree jq --exclude container-selinux

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add missing .docker folder
        run: |
          mkdir -p /github/home/.docker/

      - name: Login to Container Registry
        uses: redhat-actions/podman-login@v1
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: /tmp/auth.json

      - name: Figure out version
        id: version
        run: |
          set -exo pipefail
          if [[ -n ${VERSION_OVERRIDE} ]]; then
            version_base="${VERSION_OVERRIDE}"
          else
            version_base="$(skopeo inspect docker://${BASE_IMAGE} | jq -r '.Labels."org.opencontainers.image.version"')"
          fi
          build_date="$(date -u +"%Y%m%dT%H%M%SZ")"
          tag="${version_base}-${build_date}"
          version="${version_base}+${build_date}"
          echo "Base version: ${version_base}"
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"
          echo "version=${version}" >> "$GITHUB_OUTPUT"
        env:
          VERSION_OVERRIDE: ${{ inputs.version }}

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        id: build
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: build
          containerfiles: ${{ env.IMAGE_NAME }}/Containerfile
          context: ${{ env.IMAGE_NAME }}
          layers: true
          oci: true

      - name: Rechunk container image
        run: |
          rpm-ostree compose build-chunked-oci \
            --bootc --format-version=1 \
            --max-layers 96 \
            --from localhost/${{ steps.build.outputs.image-with-tag }} \
            --output containers-storage:localhost/${{ steps.build.outputs.image }}:rechunked

      - name: Write NOP Containerfile
        run: |
          echo "FROM localhost/${{ steps.build.outputs.image }}:rechunked" > ${{ env.IMAGE_NAME }}/Containerfile.labels
      
      - name: Add labels to container image
        uses: redhat-actions/buildah-build@v2
        id: relabel
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ steps.version.outputs.tag }}
          containerfiles: ${{ env.IMAGE_NAME }}/Containerfile.labels
          context: ${{ env.IMAGE_NAME }}
          layers: true
          oci: true
          labels: |
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
            org.opencontainers.image.title=Fedora Kinoite
            org.opencontainers.image.description=Customized image of Fedora Kinoite
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.licenses=MIT

      - name: Push to Container Registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ steps.relabel.outputs.image }}
          tags: ${{ steps.relabel.outputs.tags }}
          extra-args: |
            --compression-format=zstd

  sign-published-image:
    uses: ./.github/workflows/signing.yml
    needs: [build-image]
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    with:
      digest: ${{ needs.build-image.outputs.digest }}
      registry: ${{ needs.build-image.outputs.registry }}
      image: ${{ needs.build-image.outputs.image }}
    secrets: inherit
