name: "Sign published container image"

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      image:
        required: true
        type: string
      digest:
        required: true
        type: string

jobs:
  sign:
    runs-on: ubuntu-latest
    environment: cosign-signing
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Login to Container Registry
        run: |
          cosign login ${REGISTRY%%/*} \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }}
        env:
          REGISTRY: ${{ inputs.registry }}

      - name: Sign the published container image
        run: |
          cosign sign \
          --yes --key env://COSIGN_PRIVATE_KEY \
          ${{ inputs.registry }}/${{ inputs.image }}@${{ inputs.digest }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGSTORE_PRIVATE_KEY }}